name: WFB-ng-osd package builder for debian

on:
  push:
    branches: [ master, release-24.08 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, stable ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [11, 12]
        arch: [ "armhf.arm32v7.max", "arm64.arm64v8.cortex-a53", "amd64.amd64.max"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build package
        run: |
          curl -s -L https://github.com/svpcom/wfb-ng/releases/download/wifibroadcast-17.10/qemu-7.2.15-fixed.tar.gz | sudo tar xzv -C /
          git submodule update --init
          make deb_docker mode=gst QEMU_CPU=$(echo ${{ matrix.arch }} | cut -f3 -d.) DOCKER_ARCH=$(echo ${{ matrix.arch}} | cut -f1 -d.) DOCKER_SRC_IMAGE=$(echo ${{ matrix.arch }} | cut -f2 -d.)/debian:${{ matrix.version }}
          mv deb_dist/*.deb .
          make deb_docker mode=rockchip QEMU_CPU=$(echo ${{ matrix.arch }} | cut -f3 -d.) DOCKER_ARCH=$(echo ${{ matrix.arch}} | cut -f1 -d.) DOCKER_SRC_IMAGE=$(echo ${{ matrix.arch }} | cut -f2 -d.)/debian:${{ matrix.version }}
          mv deb_dist/*.deb .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        id: artifact-upload-step
        with:
          name: wfb-ng-osd-${{ github.ref_name }}-debian${{ matrix.version }}-${{ matrix.arch }}
          path: |
            *.deb
